In [182]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [183]:
df = pd.read_csv(r'Mental Health Dataset.csv')

In [184]:
df.shape

(292364, 17)

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Timestamp                292364 non-null  object
 1   Gender                   292364 non-null  object
 2   Country                  292364 non-null  object
 3   Occupation               292364 non-null  object
 4   self_employed            287162 non-null  object
 5   family_history           292364 non-null  object
 6   treatment                292364 non-null  object
 7   Days_Indoors             292364 non-null  object
 8   Growing_Stress           292364 non-null  object
 9   Changes_Habits           292364 non-null  object
 10  Mental_Health_History    292364 non-null  object
 11  Mood_Swings              292364 non-null  object
 12  Coping_Struggles         292364 non-null  object
 13  Work_Interest            292364 non-null  object
 14  Social_Weakness          292364 non-null  object
 15  mental_health_interview  292364 non-null  object
 16  care_options             292364 non-null  object
dtypes: object(17)
memory usage: 37.9+ MB

In [186]:
df.describe()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
count,292364,292364,292364,292364,287162,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364
unique,580,2,35,5,2,2,2,5,3,3,3,3,2,3,3,3,3
top,8/27/2014 11:43,Male,United States,Housewife,No,No,Yes,1-14 days,Maybe,Yes,No,Medium,No,No,Maybe,No,No
freq,2384,239850,171308,66351,257994,176832,147606,63548,99985,109523,104018,101064,154328,105843,103393,232166,118886

--------------------------------------------------------
DATA CLEANINIG PROCESS!
---------------------------------------------------------

In [187]:
#inserting a new column called 
df.rename(columns = {'Timestamp':'Date'},inplace=True)
df

,Date,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292359,7/27/2015 23:25,Male,United States,Business,Yes,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292360,8/17/2015 9:38,Male,South Africa,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292361,8/25/2015 19:59,Male,United States,Business,No,Yes,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292362,9/26/2015 1:07,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292363,2/1/2016 23:04,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes

In [188]:
#convert date[object] to date[datetime64[ns]]
df['Date'] = pd.to_datetime(df['Date'])

In [189]:
#adding a month/year column
df.insert(1, column = 'Month', value=df['Date'].dt.month)
df.insert(2, column = 'Year', value=df['Date'].dt.year)

In [190]:
df.set_index(['Country','Gender'])

                                    Date  Month  Year Occupation  \
Country       Gender
United States Female 2014-08-27 11:29:00      8  2014  Corporate
              Female 2014-08-27 11:31:00      8  2014  Corporate
              Female 2014-08-27 11:32:00      8  2014  Corporate
              Female 2014-08-27 11:37:00      8  2014  Corporate
              Female 2014-08-27 11:43:00      8  2014  Corporate
...                                  ...    ...   ...        ...
              Male   2015-07-27 23:25:00      7  2015   Business
South Africa  Male   2015-08-17 09:38:00      8  2015   Business
United States Male   2015-08-25 19:59:00      8  2015   Business
              Male   2015-09-26 01:07:00      9  2015   Business
              Male   2016-02-01 23:04:00      2  2016   Business

                     self_employed family_history treatment Days_Indoors  \
Country       Gender
United States Female           NaN             No       Yes    1-14 days
              Female           NaN            Yes       Yes    1-14 days
              Female           NaN            Yes       Yes    1-14 days
              Female            No            Yes       Yes    1-14 days
              Female            No            Yes       Yes    1-14 days
...                            ...            ...       ...          ...
              Male             Yes            Yes       Yes   15-30 days
South Africa  Male              No            Yes       Yes   15-30 days
United States Male              No            Yes        No   15-30 days
              Male              No            Yes       Yes   15-30 days
              Male              No            Yes       Yes   15-30 days

                     Growing_Stress Changes_Habits Mental_Health_History  \
Country       Gender
United States Female            Yes             No                   Yes
              Female            Yes             No                   Yes
              Female            Yes             No                   Yes
              Female            Yes             No                   Yes
              Female            Yes             No                   Yes
...                             ...            ...                   ...
              Male               No          Maybe                    No
South Africa  Male               No          Maybe                    No
United States Male               No          Maybe                    No
              Male               No          Maybe                    No
              Male               No          Maybe                    No

                     Mood_Swings Coping_Struggles Work_Interest  \
Country       Gender
United States Female      Medium               No            No
              Female      Medium               No            No
              Female      Medium               No            No
              Female      Medium               No            No
              Female      Medium               No            No
...                          ...              ...           ...
              Male           Low              Yes            No
South Africa  Male           Low              Yes            No
United States Male           Low              Yes            No
              Male           Low              Yes            No
              Male           Low              Yes            No

                     Social_Weakness mental_health_interview care_options
Country       Gender
United States Female             Yes                      No     Not sure
              Female             Yes                      No           No
              Female             Yes                      No          Yes
              Female             Yes                   Maybe          Yes
              Female             Yes                      No          Yes
...                              ...                     ...          ...
              Male             Maybe                   Maybe     Not sure
South Africa  Male             Maybe                      No          Yes
United States Male             Maybe                      No           No
              Male             Maybe                      No          Yes
              Male             Maybe                      No          Yes

[292364 rows x 17 columns]

In [191]:
#Counting Yes/no answers
counts = df['self_employed'].value_counts(dropna=True)
counts

No     257994
Yes     29168
Name: self_employed, dtype: int64

In [192]:
#Percentage of Yes/No answers
percentages = df['self_employed'].value_counts(normalize=True, dropna=True)
percentages

No     0.898427
Yes    0.101573
Name: self_employed, dtype: float64

In [193]:
#Filling NaNs

In [194]:
# creating a dictionary with the percentages of Yes/No answers
perc_self_employed = percentages.to_dict() 
print(perc_self_employed)

{'No': 0.8984266720527089, 'Yes': 0.10157332794729107}

In [195]:
#Nans
nans = df['self_employed'].isna()
print(nans.sum())

5202

In [196]:
df.loc[nans, 'self_employed'] = np.random.choice(
    list(perc_self_employed.keys()),
    size=nans.sum(),
    p=list(perc_self_employed.values())
)

In [197]:
#df.groupby(['Country','Gender']).count().sort_values('Gender',ascending=False)#.plot.bar(figsize=(10,8))

In [198]:
counts1 = df['self_employed'].value_counts(dropna=True)
counts1

No     262661
Yes     29703
Name: self_employed, dtype: int64

In [199]:
percentages1 = df['self_employed'].value_counts(normalize=True, dropna=True)
percentages1

No     0.898404
Yes    0.101596
Name: self_employed, dtype: float64

In [244]:
df

,Date,Month,Year,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,2014-08-27 11:29:00,8,2014,Female,United States,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,2014-08-27 11:31:00,8,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,2014-08-27 11:32:00,8,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,2014-08-27 11:37:00,8,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,2014-08-27 11:43:00,8,2014,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292359,2015-07-27 23:25:00,7,2015,Male,United States,Business,Yes,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292360,2015-08-17 09:38:00,8,2015,Male,South Africa,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292361,2015-08-25 19:59:00,8,2015,Male,United States,Business,No,Yes,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292362,2015-09-26 01:07:00,9,2015,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292363,2016-02-01 23:04:00,2,2016,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes